syntax = "proto3";

service BlockService {
  rpc GetRange(BlockParams) returns (BlockList);
  rpc GetByHeight(Block) returns (Block);
  rpc GetByHash(Block) returns (Block);
  rpc GetFirst(EmptyRequest) returns (Block);
  rpc GetLast(EmptyRequest) returns (Block);
}

message EmptyRequest {}
message BlockParams { int32 page_number = 1; int32 result_per_page = 2; }
message BlockList { repeated Block blocks = 1; }
message Block {
  int32 version = 1;
  int64 height = 2;
  int64 time_stamp = 3;
  string prev_hash = 4;
  string hash = 5;
  string transactions = 6;
  string validator = 7;
  double validator_balance = 8;
  string merkle_root = 9;
  int32 num_of_tx = 10;
  double total_amount = 11;
  double total_reward = 12;
  int32 difficulty = 13;
  int32 nonce = 14;
  int32 size = 15;
  int32 build_time = 16;
  string signature = 17;
}
